name: build

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest }
          - { os: macos-latest }
          - { os: windows-latest }

    steps:
      - uses: actions/checkout@v1
      - name: ubuntu
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libsecret-1-dev xvfb dbus-x11 gnome-keyring libsecret-tools
          sudo service dbus start
          Xvfb :99 &
          export DISPLAY=":99"

          # implicitly create the keyring
          secret-tool store --label "dummy" dummy password

      - name: build
        shell: bash
        run: |
          # enable symlinking for windows
          # (required because of patched cxx crate)
          export MSYS=winsymlinks:nativestrict
          git config --global core.symlinks true

          export DISPLAY=":99"
          git submodule update --init
          cargo test
          cargo build
